# Generated by Django 5.2.17 on 2026-09-26 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoverRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("handed_over_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_record",
                        to="donations.donation",
                    ),
                ),
                (
                    "donation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_record",
                        to="donations.donationrequest",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_records",
                        to="donations.donationrevision",
                    ),
                ),
            ],
            options={
                "db_table": "handover_records",
                "ordering": ["-handed_over_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_delivery_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_record",
                        to="donations.donation",
                    ),
                ),
                (
                    "donation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_record",
                        to="donations.donationrequest",
                    ),
                ),
                (
                    "handover",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_record",
                        to="logistics.handoverrecord",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_records",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accepted_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No discrepancy"),
                            ("SHORTAGE", "Quantity shortage"),
                            ("DAMAGE", "Damaged food or packaging"),
                            ("QUALITY", "Quality concern"),
                            ("WRONG_ITEM", "Wrong food item"),
                            ("OTHER", "Other"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("discrepancy_notes", models.TextField(blank=True)),
                ("received_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_confirmation",
                        to="logistics.deliveryrecord",
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_confirmation",
                        to="donations.donation",
                    ),
                ),
                (
                    "donation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_confirmation",
                        to="donations.donationrequest",
                    ),
                ),
                (
                    "handover",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_confirmation",
                        to="logistics.handoverrecord",
                    ),
                ),
            ],
            options={
                "db_table": "receipt_confirmations",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="handoverrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("actual_quantity__gt", 0)),
                name="handover_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("actual_quantity__gt", 0)),
                name="delivery_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptconfirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(("accepted_quantity__gte", 0)),
                name="accepted_quantity_nonnegative",
            ),
        ),
    ]
