# Generated by Django 5.2.17 on 2026-09-26 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        ("logistics", "0001_initial"),
        ("receivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pickup_area", models.CharField(max_length=100)),
                (
                    "required_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pickup_deadline", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("ARRIVED_AT_DONOR", "Arrived at donor"),
                            ("PICKED_UP", "Picked up"),
                            ("ARRIVED_AT_RECEIVER", "Arrived at receiver"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_task",
                        to="donations.donation",
                    ),
                ),
                (
                    "donation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_task",
                        to="donations.donationrequest",
                    ),
                ),
                (
                    "pickup_service_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickup_tasks",
                        to="receivers.servicearea",
                    ),
                ),
                (
                    "receiver_service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_tasks",
                        to="receivers.servicearea",
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_tasks",
                "ordering": ["pickup_deadline"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerFailureReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("BEFORE_PICKUP", "Before pickup"),
                            ("AFTER_PICKUP", "After pickup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("reassign_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_failure_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="failure_reports",
                        to="logistics.volunteertask",
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_failure_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerTaskHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_task_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="logistics.volunteertask",
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_task_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_availability",
                "ordering": ["weekday", "starts_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "weekday", "starts_at", "ends_at"),
                        name="unique_volunteer_availability",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VolunteerCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "maximum_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_capacities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_capacities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "unit"),
                        name="unique_volunteer_unit_capacity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("maximum_quantity__gt", 0)),
                        name="volunteer_capacity_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("UNAVAILABLE", "Unavailable"),
                            ("BUSY", "Busy"),
                        ],
                        db_index=True,
                        default="UNAVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "max_service_distance_km",
                    models.DecimalField(
                        decimal_places=2, default="10.00", max_digits=6
                    ),
                ),
                ("max_active_tasks", models.PositiveSmallIntegerField(default=1)),
                ("operational", models.BooleanField(default=True)),
                ("vehicle_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_profiles",
                        to="receivers.servicearea",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_profiles",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_service_distance_km__gt", 0)),
                        name="volunteer_distance_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_active_tasks__gt", 0)),
                        name="volunteer_task_limit_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="volunteertask",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_quantity__gt", 0)),
                name="volunteer_task_quantity_positive",
            ),
        ),
    ]
