# Generated by Django 5.2.17 on 2026-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REQUEST_SUBMITTED", "Request submitted"),
                    ("REQUEST_WITHDRAWN", "Request withdrawn"),
                    ("REQUEST_APPROVED", "Request approved"),
                    ("REQUEST_REJECTED", "Request rejected"),
                    ("ARRANGEMENT_CANCELLED", "Arrangement cancelled"),
                    ("DONATION_CANCELLED", "Donation cancelled"),
                    ("HANDOVER_CONFIRMED", "Handover confirmed"),
                    ("DELIVERY_RECORDED", "Delivery recorded"),
                    ("RECEIPT_CONFIRMED", "Receipt confirmed"),
                    ("RECEIPT_REJECTED", "Receipt rejected"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
