# Generated by Django 5.2.17 on 2026-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="deduplication_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REQUEST_SUBMITTED", "Request submitted"),
                    ("REQUEST_WITHDRAWN", "Request withdrawn"),
                    ("REQUEST_APPROVED", "Request approved"),
                    ("REQUEST_REJECTED", "Request rejected"),
                    ("REQUEST_EXPIRED", "Request expired"),
                    ("ARRANGEMENT_CANCELLED", "Arrangement cancelled"),
                    ("DONATION_CANCELLED", "Donation cancelled"),
                    ("DONATION_EXPIRED", "Donation expired"),
                    ("HANDOVER_CONFIRMED", "Handover confirmed"),
                    ("DELIVERY_RECORDED", "Delivery recorded"),
                    ("RECEIPT_CONFIRMED", "Receipt confirmed"),
                    ("RECEIPT_REJECTED", "Receipt rejected"),
                    ("RECEIPT_REMINDER", "Receipt confirmation reminder"),
                    ("PICKUP_REMINDER", "Pickup reminder"),
                    ("PICKUP_OVERDUE", "Pickup overdue"),
                    ("VOLUNTEER_TASK_ASSIGNED", "Volunteer task assigned"),
                    ("VOLUNTEER_PICKUP", "Volunteer pickup"),
                    ("VOLUNTEER_DELIVERY", "Volunteer delivery"),
                    ("VOLUNTEER_TASK_FAILED", "Volunteer task failed"),
                    ("VOLUNTEER_TASK_REASSIGNED", "Volunteer task reassigned"),
                    ("ACCOUNT_SUSPENDED", "Account suspended"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
