# Generated by Django 5.2.17 on 2026-09-26 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        ("logistics", "0002_volunteertask_volunteerfailurereport_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=255, unique=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[("SEND_NOTIFICATION", "Send notification")],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("run_after", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("last_error", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "background_jobs",
                "ordering": ["run_after", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after"], name="background_job_due_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gt", 0)),
                        name="background_job_attempt_limit_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationalIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=255, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("MISSED_PICKUP", "Missed pickup"),
                            ("VOLUNTEER_CANCELLATION", "Volunteer cancellation"),
                            ("TRANSPORT_FAILURE", "Transport failure"),
                            ("DELIVERY_REJECTED", "Delivery rejected"),
                            ("RECEIPT_OVERDUE", "Receipt confirmation overdue"),
                            ("ACCOUNT_SUSPENDED", "Participant account suspended"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_issues",
                        to="donations.donation",
                    ),
                ),
                (
                    "donation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_issues",
                        to="donations.donationrequest",
                    ),
                ),
                (
                    "volunteer_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_issues",
                        to="logistics.volunteertask",
                    ),
                ),
            ],
            options={
                "db_table": "operational_issues",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "issue_type"], name="op_issue_status_type_idx"
                    )
                ],
            },
        ),
    ]
