# Generated by Django 5.2.17 on 2026-09-27 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[("RULE_BASED_V1", "Explainable weighted baseline v1")],
                        default="RULE_BASED_V1",
                        max_length=40,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="baseline-1.0", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        db_index=True,
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("weights", models.JSONField(default=dict)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_runs",
                        to="donations.donation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_recommendation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_runs",
                        to="donations.donationrevision",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "approximate_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "remaining_capacity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("feature_snapshot", models.JSONField(default=dict)),
                ("explanations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="recommendations.recommendationrun",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_candidates",
                "ordering": ["rank"],
            },
        ),
        migrations.AddIndex(
            model_name="recommendationrun",
            index=models.Index(
                fields=["donation", "-created_at"], name="rec_run_donation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationcandidate",
            index=models.Index(fields=["run", "rank"], name="rec_candidate_run_idx"),
        ),
        migrations.AddConstraint(
            model_name="recommendationcandidate",
            constraint=models.UniqueConstraint(
                fields=("run", "receiver"), name="unique_receiver_per_rec_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationcandidate",
            constraint=models.UniqueConstraint(
                fields=("run", "rank"), name="unique_rank_per_rec_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="rec_score_between_0_100",
            ),
        ),
    ]
