# Generated by Django 5.2.17 on 2026-09-28 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("eligible", models.BooleanField(db_index=True, default=False)),
                ("rejection_reasons", models.JSONField(blank=True, default=list)),
                ("eligibility_checks", models.JSONField(default=dict)),
                ("feature_snapshot", models.JSONField(default=dict)),
                (
                    "baseline_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendation_evaluations",
                "ordering": ["-eligible", "-baseline_score", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="recommendationrun",
            name="considered_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recommendationrun",
            name="eligible_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recommendationrun",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("RULE_BASED_V1", "Explainable weighted baseline v1"),
                    ("RULE_BASED_V2", "Normalized weighted baseline v2"),
                    ("ML_COMPLETION_V1", "Completion probability model v1"),
                ],
                default="RULE_BASED_V2",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="recommendationrun",
            name="model_version",
            field=models.CharField(default="baseline-2.0", max_length=50),
        ),
        migrations.AddIndex(
            model_name="recommendationrun",
            index=models.Index(
                fields=["algorithm", "-created_at"], name="rec_run_algo_idx"
            ),
        ),
        migrations.AddField(
            model_name="recommendationevaluation",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommendation_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationevaluation",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="recommendations.recommendationrun",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationevaluation",
            index=models.Index(
                fields=["run", "eligible"], name="rec_eval_run_eligible_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationevaluation",
            constraint=models.UniqueConstraint(
                fields=("run", "receiver"), name="unique_rec_eval_receiver"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("baseline_score__isnull", True),
                    models.Q(("baseline_score__gte", 0), ("baseline_score__lte", 100)),
                    _connector="OR",
                ),
                name="rec_eval_score_0_100",
            ),
        ),
    ]
