# Generated by Django 5.2.17 on 2026-09-28 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        ("recommendations", "0002_recommendationevaluation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchTrainingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dataset_source",
                    models.CharField(
                        choices=[
                            ("REAL", "Real platform data"),
                            ("SYNTHETIC", "Synthetically generated data"),
                            ("PILOT", "Pilot/testing data"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "target_completed",
                    models.BooleanField(
                        db_index=True,
                        help_text="True only when the donation reached confirmed COMPLETED status.",
                    ),
                ),
                ("approved_at", models.DateTimeField()),
                ("outcome_at", models.DateTimeField()),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "feature_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Immutable features captured at recommendation time.",
                    ),
                ),
                ("baseline_version", models.CharField(max_length=50)),
                (
                    "baseline_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("recommendation_timestamp", models.DateTimeField()),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_record",
                        to="donations.donationrequest",
                    ),
                ),
                (
                    "recommendation_evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_records",
                        to="recommendations.recommendationevaluation",
                    ),
                ),
            ],
            options={
                "db_table": "match_training_records",
                "ordering": ["approved_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_source", "target_completed"],
                        name="train_source_target_idx",
                    ),
                    models.Index(fields=["approved_at"], name="train_approved_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome_at__gte", models.F("approved_at"))
                        ),
                        name="train_outcome_after_approval",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("baseline_score__isnull", True),
                            models.Q(
                                ("baseline_score__gte", 0), ("baseline_score__lte", 100)
                            ),
                            _connector="OR",
                        ),
                        name="train_score_0_100",
                    ),
                ],
            },
        ),
    ]
