# Generated by Django 5.2.17 on 2026-09-26 05:43

import apps.moderation.models
import apps.moderation.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_details", models.JSONField(default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verification_submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                            ("REOPENED", "Reopened"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="moderation.verificationsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "verification_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("IDENTITY", "Identity document"),
                            ("ORGANIZATION_REGISTRATION", "Organization registration"),
                            ("ADDRESS_PROOF", "Address proof"),
                            ("OTHER", "Other document"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        storage=apps.moderation.storage.PrivateVerificationStorage(),
                        upload_to=apps.moderation.models.verification_document_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="moderation.verificationsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "verification_documents",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="verificationsubmission",
            constraint=models.UniqueConstraint(
                fields=("user", "attempt"), name="unique_verification_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("user",),
                name="one_pending_verification_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gt", 0)),
                name="verification_attempt_positive",
            ),
        ),
    ]
