# Generated by Django 5.2.17 on 2026-09-27 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("DONATION", "Donation"),
                            ("TRANSPORT", "Transport"),
                            ("PARTICIPANT", "Participant"),
                            ("VERIFICATION", "Verification"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="donations.donation",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "complaints",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="complaint_status_idx"
                    ),
                    models.Index(
                        fields=["reporter", "created_at"], name="complaint_reporter_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reported_user__isnull", True),
                            models.Q(
                                ("reported_user", models.F("reporter")), _negated=True
                            ),
                            _connector="OR",
                        ),
                        name="complaint_not_self",
                    )
                ],
            },
        ),
    ]
