# Generated by Django 5.2.17 on 2026-09-28 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donationrequest_one_approved_request_per_donation"),
        ("moderation", "0002_complaint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_DOWNLOADED", "Private document downloaded"),
                            ("COMPLAINT_UPDATED", "Complaint updated"),
                            ("ACCOUNT_DEACTIVATED", "Account deactivated"),
                            ("OUTCOME_CORRECTED", "Donation outcome corrected"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(db_index=True, max_length=80)),
                ("target_id", models.CharField(db_index=True, max_length=100)),
                ("reason", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="audit_action_created_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="audit_target_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutcomeCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("old_closed_at", models.DateTimeField(blank=True, null=True)),
                ("new_closed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcome_corrections",
                        to="donations.donation",
                    ),
                ),
            ],
            options={
                "db_table": "outcome_corrections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["donation", "created_at"], name="outcome_donation_idx"
                    )
                ],
            },
        ),
    ]
