# Generated by Django 5.2.17 on 2026-09-26 08:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0003_donationrevision_pickup_area_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReceiverProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_name", models.CharField(max_length=180)),
                ("address", models.TextField()),
                (
                    "max_service_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.10")),
                            django.core.validators.MaxValueValidator(Decimal("200.00")),
                        ],
                    ),
                ),
                (
                    "max_active_allocations",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("operational", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_profiles",
                        to="receivers.servicearea",
                    ),
                ),
            ],
            options={
                "db_table": "receiver_profiles",
                "ordering": ["organization_name"],
            },
        ),
        migrations.CreateModel(
            name="ReceiverAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receiver_availability",
                "ordering": ["weekday", "starts_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receiver", "weekday", "starts_at", "ends_at"),
                        name="unique_receiver_availability",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReceiverPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_preferences",
                        to="donations.foodcategory",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receiver_preferences",
                "ordering": ["category__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receiver", "category"),
                        name="unique_receiver_food_preference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReceiverRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_needed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                    ),
                ),
                ("needed_until", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_requirements",
                        to="donations.foodcategory",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receiver_requirements",
                "ordering": ["category__name", "unit"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receiver", "category", "unit"),
                        name="unique_receiver_requirement",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_needed__gt", 0)),
                        name="receiver_quantity_needed_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_reserved__gte", 0)),
                        name="receiver_quantity_reserved_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity_reserved__lte", models.F("quantity_needed"))
                        ),
                        name="receiver_reserved_not_above_needed",
                    ),
                ],
            },
        ),
    ]
