# Generated by Django 5.2.17 on 2026-09-25 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Food categories",
                "db_table": "food_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("PICKED_UP", "Picked up"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("custody_hold", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("food_name", models.CharField(max_length=160)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("LITRE", "Litre"),
                            ("PORTION", "Portion"),
                            ("PACKAGE", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("storage_condition", models.CharField(blank=True, max_length=100)),
                ("pickup_address", models.TextField()),
                ("pickup_starts_at", models.DateTimeField()),
                ("pickup_deadline", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="donations.donation",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_donation_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation_revisions",
                        to="donations.foodcategory",
                    ),
                ),
            ],
            options={
                "db_table": "donation_revisions",
                "ordering": ["donation", "-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("donation", "number"),
                        name="unique_donation_revision_number",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("donation",),
                        name="one_current_revision_per_donation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="donation_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("pickup_deadline__gt", models.F("pickup_starts_at"))
                        ),
                        name="pickup_deadline_after_start",
                    ),
                ],
            },
        ),
    ]
