# Generated by Django 5.2.17 on 2026-09-26 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_donationrevision_pickup_area_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="donationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "APPROVED")),
                fields=("donation",),
                name="one_approved_request_per_donation",
            ),
        ),
    ]
